image: docker.adeo.no:5000/fo/veilarbvedtakinfo
team: bos
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarbvedtakinfo/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbvedtakinfo/internal/isReady
    initialDelay: 20
prometheus:
  enabled: true
  path: veilarbvedtakinfo/internal/metrics
resources:
  limits:
    cpu: 3
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

fasitResources:
  used:
  - alias: appdynamics
    resourceType: applicationproperties

  # custom veilarbdirigent props
  - alias: loadbalancer:veilarbvedtakinfo
    resourceType: loadbalancerconfig
  - alias: srvveilarbvedtakinfo
    resourceType: credential
  - alias: veilarbvedtakinfoDB
    resourceType: datasource

  # external resources used
  - alias: Aktoer_v2
    resourceType: webserviceendpoint
  - alias: abac.pdp.endpoint
    resourceType: restservice


  # security resources
  - alias: isso-rp-user
    resourceType: credential
  - alias: isso-host
    resourceType: baseUrl
  - alias: isso-jwks
    resourceType: baseUrl
  - alias: isso-issuer
    resourceType: baseUrl
  - alias: isso.isalive
    resourceType: baseUrl
  - alias: veilarblogin.redirect-url
    resourceType: restservice
  - alias: aad_b2c_clientid
    resourceType: credential
  - alias: aad_b2c_discovery
    resourceType: baseurl

  exposed:
  - alias: veilarbvedtakinfoAPI
    resourceType: restservice
    path: /veilarbvedtakinfo/api
alertProfiles:
  - common-java-modules