kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtakinfo
  namespace: pto
  labels:
    team: obo
spec:
  image: ghcr.io/navikt/veilarbvedtakinfo/veilarbvedtakinfo:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://app.adeo.no/veilarbvedtakinfo
    - https://veilarbvedtakinfo.nais.adeo.no
    - https://veilarbvedtakinfo.prod-fss-pub.nais.io
  prometheus:
    enabled: true
    path: veilarbvedtakinfo/internal/prometheus
  readiness:
    path: veilarbvedtakinfo/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtakinfo/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: prod-fss
        - application: start-samtale
          namespace: pto
          cluster: prod-gcp
        - application: aia-backend
          namespace: paw
          cluster: prod-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvveilarbvedtakinfo
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/prod/creds/veilarbvedtakinfo_p-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/prod/fss/veilarbvedtakinfo/default
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/prod/config/veilarbvedtakinfo_p
        mountPath: /var/run/secrets/nais.io/oracle_config
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
