kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtakinfo
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbvedtakinfo/veilarbvedtakinfo:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://app-q1.adeo.no/veilarbvedtakinfo
    - https://veilarbvedtakinfo-q1.nais.preprod.local
  prometheus:
    enabled: true
    path: veilarbvedtakinfo/internal/prometheus
  readiness:
    path: veilarbvedtakinfo/internal/health/readiness
    initialDelay: 30
  liveness:
    path: veilarbvedtakinfo/internal/health/liveness
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: veilarbvedtaksstotte
          namespace: pto
          cluster: dev-fss
        - application: start-samtale
          namespace: pto
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbvedtakinfo
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/creds/veilarbvedtakinfo_q1-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarbvedtakinfo/q1
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /oracle/data/dev/config/veilarbvedtakinfo_q1
        mountPath: /var/run/secrets/nais.io/oracle_config
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
