kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbvedtakinfo
  namespace: {{namespace}}
  labels:
    team: pto
  cluster: dev-fss
spec:
  image: docker.pkg.github.com/navikt/veilarbvedtakinfo/veilarbvedtakinfo:{{version}}
  port: 8080
  webproxy: true
  ingresses:
    - https://app-{{namespace}}.adeo.no/veilarbvedtakinfo
    - https://veilarbvedtakinfo-{{namespace}}.nais.preprod.local
  prometheus:
    enabled: true
    path: veilarbvedtakinfo/internal/prometheus
  readiness:
    path: veilarbvedtakinfo/internal/isReady
    initialDelay: 30
  liveness:
    path: veilarbvedtakinfo/internal/isAlive
    initialDelay: 30
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvveilarbvedtakinfo
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /oracle/data/dev/creds/veilarbvedtakinfo_{{namespace}}-user
        mountPath: /var/run/secrets/nais.io/oracle_creds
      - kvPath: /kv/preprod/fss/veilarbvedtakinfo/{{namespace}}
        mountPath: /var/run/secrets/nais.io/vault
  envFrom:
    - configmap: pto-config
