CREATE SEQUENCE FREMTIDIG_SITUASJON_SEQ;

CREATE TABLE FREMTIDIG_SITUASJON (
  FREMTIDIG_SITUASJON_ID NUMBER,
  AKTOR_ID VARCHAR(20) NOT NULL,
  ALTERNATIV_ID VARCHAR(30),
  TEKST VARCHAR(500),
  ENDRET_AV VARCHAR(20),
  DATO TIMESTAMP(6) NOT NULL,

  CONSTRAINT "FREMTIDIG_SITUASJON_ID_PK" PRIMARY KEY ("FREMTIDIG_SITUASJON_ID")
);