CREATE SEQUENCE BEHOVSVURDERING_SEQ;

CREATE TABLE BEHOVSVURDERING_BESVARELSE (
  BESVARELSE_ID  NUMBER,
  AKTOR_ID       NVARCHAR2(20) NOT NULL,
  SIST_OPPDATERT TIMESTAMP(6)  NOT NULL,

  CONSTRAINT "BESVARELSE_ID_PK" PRIMARY KEY ("BESVARELSE_ID")
);

CREATE TABLE BEHOVSVURDERING_SPORSMAL_SVAR (
  BESVARELSE_ID NUMBER       NOT NULL,
  SPM_ID        NVARCHAR2(255),
  SPM           NVARCHAR2(2000),
  SVAR          NVARCHAR2(2000),
  DATO          TIMESTAMP(6) NOT NULL,
  CONSTRAINT SPM_SVAR_FK FOREIGN KEY (BESVARELSE_ID) REFERENCES BEHOVSVURDERING_BESVARELSE
);
