CREATE SEQUENCE MIN_SITUASJON_SEQ;


create table MIN_SITUASJON
(
    ID  NUMBER NOT NULL,
    AKTOR_ID NVARCHAR2(20) NOT NULL,
    OPRETTET TIMESTAMP(6)  NOT NULL,
    ENDRET_AV NVARCHAR2(20) NOT NULL,
    SVAR_ID NVARCHAR2(20) NOT NULL,
    SVAR_TEXT NVARCHAR2(255) NOT NULL,

    CONSTRAINT "MIN_SITUASJON_ID_PK" PRIMARY KEY ("ID")
);

create index SituasjonIndex on MIN_SITUASJON(ENDRET_AV, AKTOR_ID);

select * from MIN_SITUASJON where AKTOR_ID = ? order by OPRETTET desc;
