name: Test
run-name: Test PR ${{ github.event.pull_request.title }} by @${{ github.actor }}
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Run maven tests
        run: mvn -B verify